abc = {'a':'4',
       'b':'|3',
       'c':'[',
       'd':')',
       'e':'3',
       'f':'|=',
       'g':'&',
       'h':'#',
       'i':'1',
       'j':',_|',
       'k':'<|',
       'l':'1',
       'm':"/\\/\\",
       'n':'^/',
       'o':'0',
       'p':'|*',
       'q':'(_,)',
       'r':'|2',
       's':'5',
       't':'7',
       'u':'(_)',
       'v':'\/',
       'w':'\/\/',
       'x':'><',
       'y':'j',
       'z':'2'}

cadena = input("Introduce una frase: ")
cadenaHack = [abc.get(l) if abc.get(l) is not None else '-' for l in cadena]
print(cadenaHack)